FROM node:12.7-stretch

RUN mkdir -p /code
WORKDIR /code/

ADD package.json /code
RUN npm install

COPY gulpfile.js tailwind.config.js /code/
COPY theme/assets/ /code/theme/assets/

ENTRYPOINT ["npm"]
